### ISSUE TITLE
Can't hit Endermen when Minefantasy 2 is installed alongside DragonAPI

### ISSUE THREAD

**Issue by tehFoxx0rz** [Sirse/MineFantasyII-Cont#1]
When I have both Minfantasy 2 (version 2.8.12, link to the mod here ) and DragonAPI (17b, but previous versions too) installed, Endermen seem unable to register damage coming from the player - punching them causes nothing to happen, and for non-melee things like the shock focus from Thaumcraft, too. It seems to register client-side perhaps (for punching at least), since their mouth briefly opens like they're angry, but only for a brief instant before the Enderman continues acting peaceful as if nothing happened.

In my testing this seems to be possible to replicate with only DragonAPI and Minefantasy 2 installed and nothing else. Unsure if anything was reported relevant to this in the log, but here it is in case it can help: https://pastebin.com/rRASdkFE

Also using Forge version 10.13.4.1614.

Crossposting from https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/1438 - thanks!

**Comment by Sirse** [comment]
Can you attach logfile with enabled debugging (just put key AU32-Db42-Acf6-Ggh9-9E8d in config)?

**Comment by tehFoxx0rz** [comment]
Here: https://www.dropbox.com/s/7y21imamifsh9eb/fml-client-latest.log?dl=0

I simply opened the game then a world, summoned an Enderman and punched it twice, and then exited, if that helps to say!

**Comment by Sirse** [comment]
Thx. According to your log MF are listen damage event and calculated damage values:

> [14:04:10] [Server thread/INFO] [FML/]: [MineFantasyII]: (debug) 1.0x Blunt Damage inflicted to: Enderman (437)
[14:04:10] [Server thread/INFO] [FML/]: [MineFantasyII]: (debug) 1.0x Blunt Damage inflicted to: Enderman (437)

I will debug it little bit later.

**Comment by waig548** [comment]
I just discovered something interesting: It seems only the katana can deal damages to endermen if DragonAPI is present.

**Comment by Sirse** [comment]
[MineFantasyII-2.8.13.1u.zip](https://github.com/Sirse/MineFantasyII-Cont/files/1184821/MineFantasyII-2.8.13.1u.zip)

Try latest build, please (unzip package, GitHub don't allows to upload JAR files directly).
I dont't know why DragonAPI ASM patch breaks MF hitspeed system, that fix are just hack.

**Comment by tehFoxx0rz** [comment]
This seems to have fixed it! Thank you!

**Comment by Sirse** [comment]
NP
