### ISSUE TITLE
not an issue but a request

### ISSUE THREAD

**Issue by TandJ21** [Sirse/MineFantasyII-Cont#11]
is there anyway you can get your version accepted onto curse so i can put the latest version in my modpack cos other wise the public release will stay broken (because of all the pig iron derps etc.) or is there any way i can put it my pack and curse will accept it my pack can be found here https://minecraft.curseforge.com/projects/minerpg-the-ultimate-rpg-experience

if i need to change launchers from twitch to technic launcher for it to work i will

**Comment by Sirse** [comment]
I'm started new project here - https://minecraft.curseforge.com/projects/minefantasy-ii-unofficial
On moderation now.

**Comment by Sirse** [comment]
Unfortunately, CurseForge moderator rejected mod. CF projects should be published by original author.

**Comment by TandJ21** [comment]
its because u have it as all rights reserved on your github the mods to be under a license that aloows anybody to use it in a modpack

**Comment by Sirse** [comment]
Mainfork (AnonymousProductions/MineFantasyII-Cont) are unlicensed. Only AP can add GNU GPL license to their fork or give me CF project permissions.
