### ISSUE TITLE
There is a Modpack

### ISSUE THREAD

**Issue by wolfyez** [Sirse/MineFantasyII-Cont#12]
I created a modpack with this mod in it, i want you to try it out. and when other people are playing it they get confused right away. i was like this at first not knowing what to do without tutorials and i just followed by the book. this is one of my favorite mods that changes up crafting.

**Comment by wolfyez** [comment]
if you want to play the modpack, i will send you a download like. I would love you it with you, lots of people say your mod is addicting

**Comment by Sirse** [comment]
Are you posted your modpack in any platform (CurseForge)? I can add link to mainpage.

**Comment by wolfyez** [comment]
No, it's in technic. and i want to get back to working on it during the
summer.

**Comment by wolfyez** [comment]
https://www.technicpack.net/modpack/peasants-of-kings-pov.1082681
