### ISSUE TITLE
Oven can't cook stove items.

### ISSUE THREAD

**Issue by tehFoxx0rz** [Sirse/MineFantasyII-Cont#19]
I've had this issue since I started playing the 1.7.10 version of MF2 but it doesn't really cause many practical problems so I overlooked it, but the wording in the book indicates that the oven is meant to be able to cook all the food that the stovetop can. This is currently not the case; I can't even put things like meat or potatoes inside the oven.

Additionally, I seem to still be able to bake clay items like the clay pot in a furnace, when it's indicated in the book that they're meant to be fired in the oven. 

Thanks!

**Comment by Sirse** [comment]
Fixed via f57029ec9df7b54e2140b9966d5fcb93ebc78033

Clay baking in vanilla furnaces now can disabled via "Prevent furnace food" boolean in ConfigHardcore.
