### ISSUE TITLE
Difference in NBT format for timbers received from salvage station

### ISSUE THREAD

**Issue by tehFoxx0rz** [Sirse/MineFantasyII-Cont#20]
Timbers acquired through crafting have lowercase NBT tags for their wood type, whereas timbers got from using the salvage station have uppercase letters.

Gained through regular crafting:
<minefantasy2:MF_Com_plank>.withTag({MF_CustomMaterials: {main_metal: "refinedwood"}})
Gained through salvage station:
<minefantasy2:MF_Com_plank>.withTag({MF_CustomMaterials: {main_metal: "RefinedWood"}})

Unsure if this extends to ingots or other items but I don't believe it does.

**Comment by Sirse** [comment]
Thats are causes any issues except unstackable items?

**Comment by AnonymousProductions** [comment]
Still probably good to fix it anyway, not game breaking- but it is a pain not allowing them to stack together.

**Comment by Sirse** [comment]
Closed via https://github.com/Sirse/MineFantasyII-Cont/commit/26f608610e0f6fd42f8d7ea281f762c22859df78
