### ISSUE TITLE
Carpenter Bench Recipes Don't Respect Timber Type

### ISSUE THREAD

**Issue by azacock** [Sirse/MineFantasyII-Cont#21]
I'm trying to add some recipes to the carpenter's bench:

```
CraftingManagerCarpenter.getInstance().addRecipe(new ItemStack(GameRegistry.findItem("ExtraTiC", "toolrod"), 1, 134), SkillList.artisanry, "", "", 10f, "knife", 0, 0, 1, new Object[] {"xx", 'x', ComponentListMF.plank.construct("Bloodwood")});
CraftingManagerCarpenter.getInstance().addRecipe(TConstructRegistry.getPartMapping(TConstructRegistry.getItem("woodPattern"), 1, 0), SkillList.artisanry, "", "", 10f, "knife", 0, 0, 1, new Object[] {"xx", 'x', ComponentListMF.plank.construct("Oak")});
```

The expected behavior would be that 2 bloodwood timbers would create a bloodwood tool rod, and 2 oak timbers would create a wooden tool rod. However, ANY two timbers result in a wooden tool rod.

**Comment by Sirse** [comment]
Please, post minetweaker hand command output (on crafting result rod)

**Comment by azacock** [comment]
```
<TConstruct:toolRod>
Is in <ore:woodRod>
Is in <ore:rodWood>
```

Be aware though, this isn't a MineTweaker script. It's Java.

**Comment by Sirse** [comment]
You should use material name "OakWood" instead "Oak".
Also, Bloodwood should be registered in MF via WoodMaterial.getOrAddWood() method.

**Comment by azacock** [comment]
I was using CustomMaterial.getOrAddMaterial() to register wood and metals. I'll use WoodMaterial for wood, then. Is there another class or function I should be using for metals, or is CustomMaterial the recommended way?

**Comment by Sirse** [comment]
CustomMaterial are parent class for WoodMaterial, LeatherMaterial and MetalMaterial classes and their usage are prefered, but not required.

Your problem caused by material name mismatch (if material name don't registered any item will be acceptable). Check your names twice)

**Comment by Sirse** [comment]
Semifixed in https://github.com/Sirse/MineFantasyII-Cont/commit/26f608610e0f6fd42f8d7ea281f762c22859df78, full fix after NEI handlers update
