### ISSUE TITLE
MineFantasy2 Weapon skins (Armorers Worshop support)

### ISSUE THREAD

**Issue by Cinamonfire** [Sirse/MineFantasyII-Cont#22]
i can skin MF2 Armor with your mod but i cant skin the weapons, i want you to contact riskyken the dev of armorers workshop since theres a problem with the weapon skins renderer for both mods...

please make a compatibility with the mods

Heres the post i made months ago about the issue for riskyken

https://github.com/RiskyKen/Armourers-Workshop/issues/181

**Comment by Sirse** [comment]
https://filecloud.me/aduzw24cmqdy.html - try that build, please

**Comment by Cinamonfire** [comment]
It doesnt display the build and the folder is empty :(

Edit: Can i have your discord? and sorry I wasnt Available this month...

**Comment by Sirse** [comment]
@Cinamonfire, sry for long answer. Try install latest version - https://github.com/Sirse/MineFantasyII-Cont/releases/tag/2.8.14.4u
Yes, you can find me - Sirse#8103
