### ISSUE TITLE
1.7.10 Game Initialize Crash

### ISSUE THREAD

**Issue by egeozyuvaci** [Sirse/MineFantasyII-Cont#28]
Hellllo, we are having initializing issues for 1.7.10. Game crash at 2/7 initialize stage. Only mod is MF2 with latest forge and java. Any recommendations? Ty!

**Comment by Sirse** [comment]
https://nofile.io/f/Y3M8A7NwPe1/MineFantasyII-2.8.14.5u.jar

Try to install that version and attach logs (from logs and crash-logs dirs).

**Comment by egeozyuvaci** [comment]
Oh, already using that version. Good Luck bro thank you.
[latest.log](https://github.com/Sirse/MineFantasyII-Cont/files/2006848/latest.log)

[crash-2018-05-16_00.47.36-client.txt](https://github.com/Sirse/MineFantasyII-Cont/files/2006847/crash-2018-05-16_00.47.36-client.txt)

**Comment by Sirse** [comment]
Very strange bug, i was added nullcheck, please, try it - https://nofile.io/f/hMvqakq6Ssk/MineFantasyII-2.8.14.6u.jar

**Comment by egeozyuvaci** [comment]
Unfortunately it crashes at 6/7 bu we took a step! Thanks :D
https://cdn.discordapp.com/attachments/441707189854535680/446303012823236609/crash-2018-05-16_16.28.20-client.txt

**Comment by Sirse** [comment]
This not fix, but I added log output which can help to resolve that issue.
Just download and attach both logs after crash https://nofile.io/f/tTT6Y4UFX8Q/MineFantasyII-2.8.14.6u.jar

**Comment by egeozyuvaci** [comment]
U da best
[latest-2.log](https://github.com/Sirse/MineFantasyII-Cont/files/2009984/latest-2.log)
[crash-2018-05-16_19.32.33-client.txt](https://github.com/Sirse/MineFantasyII-Cont/files/2009983/crash-2018-05-16_19.32.33-client.txt)

**Comment by Sirse** [comment]
What program is ur using for launch game?
Try to remove all these java arguments:
`-XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M`

**Comment by egeozyuvaci** [comment]
Tried the latest launcher and the old one. I don’t know how to remove those arguments but ill figure it out thanks bud.

**Comment by Sirse** [comment]
Invalid launch arguments
