### ISSUE TITLE
Handpick bonus loot ignoring meta

### ISSUE THREAD

**Issue by Ghostlyr** [Sirse/MineFantasyII-Cont#35]
Any ore block having metadata may drop loot from parent block with 0 meta on breaking by handpick.

Example: Biomes O' Plenty Topaz ore (gemOre:5) dropping a topaz gem (gem:5) and bonus (gems:0) from Ender Amethyst Ore.

MF 2.8.14.5
Forge 1.7.10 1614
BOP 2.1.0.2308

![2018-08-20_01 41 29](https://user-images.githubusercontent.com/8511068/44312537-c1f60c00-a41b-11e8-9ef3-ad4ef53955bf.png)
![2018-08-20_01 41 11](https://user-images.githubusercontent.com/8511068/44312538-c1f60c00-a41b-11e8-9390-6fde55045d2c.png)

**Comment by Sirse** [comment]
Closed via https://github.com/Sirse/MineFantasyII-Cont/commit/e8ee0cf4d8608d375773a2714d97da31ed15e7f0
