### ISSUE TITLE
I've edited MF2 and added support for some metallurgy metals and new weapons

### ISSUE THREAD

**Issue by Kacpros** [Sirse/MineFantasyII-Cont#36]
So i've added a support for some metallurgy metals like:
- Atlarus
- Orichalcum
- Vulcanite
- Platinum
- Haderoth
- Damascus Steel
- Tartarite
- Angmallen
- Shadow Iron
And non-metallurgy metal: Dwarven Steel.
*Added mithril ore that will generate in the world.
*Added 4 new weapons:
- Longsword
- Saber
- Gladius
- Shortsword

I've started working on it about 2 days ago and im gonna add more weapons, more metals and ores, more armors like dwarven armor and roman armor, maybe new mobs etc.
If somebody intrested here's download link:

https://mega.nz/#!o3YWEKZZ!zjQrQStT2PPD4IMFInBRnjU7OSDJokvuf5QyMHkSkLY

btw. sorry for my bad english but im from Poland.
Minefantasy2 is the greatest mod that i've ever seen.

**Comment by Sirse** [comment]
Duplicated #37
