### ISSUE TITLE
@Sirse can i get permission to upload edited version of MF2?

### ISSUE THREAD

**Issue by Kacpros** [Sirse/MineFantasyII-Cont#37]
@Sirse please give me permission to upload my edited version of MF2. I've added 7 new weapons,
metallurgy metals support etc.

**Comment by Sirse** [comment]
You should make a pull request - https://github.com/Sirse/MineFantasyII-Cont/pulls

**Comment by Kacpros** [comment]
What i should write in a pull request?

**Comment by Sirse** [comment]
Information about changes in your code.
I will review your version and push it into main branch.

**Comment by Kacpros** [comment]
ok

**Comment by Kacpros** [comment]
i have compiled mod i can give you link to it and source

**Comment by Kacpros** [comment]
i can upload source code on website

**Comment by Kacpros** [comment]
Ok i've made pull request

**Comment by Kacpros** [comment]
@Sirse I've created new MF2 logo too here's link: https://imgur.com/a/aY0ey8q Its 400x400px so perfect for logo on curseforge

**Comment by Kacpros** [comment]
@Sirse what do you think about that?

**Comment by Sirse** [comment]
You was made PR into AP repo, I don’t have permission to original repository.
Please, make a pr into my repository

**Comment by Kacpros** [comment]
@Sirse i cant make pull request in your repository. It automatically transport me to AnonymousProductions' repository :(

**Comment by Kacpros** [comment]
@Sirse ok i did it

**Comment by Sirse** [comment]
Merged into separate branch, after testing on my server i will merge it to master and release un Curse.
