### ISSUE TITLE
Crash when trying to read Knowledge Talisman in Basic Info tab

### ISSUE THREAD

**Issue by syndicate25** [Sirse/MineFantasyII-Cont#40]
Can't read the Knowledge Talisman section of the Research Book..  Causes instant crash when clicking on it.

https://pastebin.com/mYqzzXN6

**Comment by Kradis137** [comment]
you know how to fix the research book? 
it doesnt let me do any reaserch and i have sufficent level requirements.

**Comment by syndicate25** [comment]
Please don't add comments to other issues just to get answers to your questions. Use the minecraft forum thread for that. This is for reporting and tracking issues.

**Comment by Kradis137** [comment]
Sorry. Plz help me with my problem

**Comment by Sirse** [comment]
Closed via https://github.com/Sirse/MineFantasyII-Cont/commit/8cc847a10d2f404deeaba7028d77c14008b5e17a
