### ISSUE TITLE
Research book cant research

### ISSUE THREAD

**Issue by Kradis137** [Sirse/MineFantasyII-Cont#41]
I have the level requirements but when i try to research something in the book it doesnt do anithing
![capture](https://user-images.githubusercontent.com/45113162/48655507-73312180-e9cc-11e8-9924-07c213b776e9.PNG)
![capture1](https://user-images.githubusercontent.com/45113162/48655508-73c9b800-e9cc-11e8-8ea6-9d87236d3aa7.PNG)

**Comment by syndicate25** [comment]
You don't do research in the book. It's a guide to show you where you can go next and what paths you need to take to get what you want. Use the Research Table to do research.

**Comment by Kradis137** [comment]
Yes...but I need to unlock the research in the book then I need to place
the scroll in the research table to make the research.

If I don't unlock the tabs on the book how would I know how to do things?

**Comment by syndicate25** [comment]
You are not using the research table correctly. 

You don't put scrolls in the table. You put researchable items in it, which unlock new technologies after you've researched all the correct components for that particular technology. For example, put a feather in the research table and you will get 1/3 research completed for arrows, I believe.
