### ISSUE TITLE
Underground Biomes compatibility

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [Sirse/MineFantasyII-Cont#42]
It is not possible to acquire sharp rocks by breaking Underground Biomes Constructs rocks with your hand. It is also not possible to process UBC vanilla ores or UBC ore registrar ores in the Bloomery.

**Comment by Sirse** [comment]
Closed via https://github.com/Sirse/MineFantasyII-Cont/commit/cb685bd1acce0751a76b939f35b7dbbeefc80028

**Comment by bHXDgiuMa5yLHyC8** [comment]
It's great to see some progress on this. The bloomery recipes are not really an issue, but the handpick does not give bonus drops with UBC stones and UBC vanilla ores. Also the recipes that use smooth stone and cobblestone are lacking oredictionary support, and I cannot figure out how to use the carpenter minetweaker function to add them myself.

**Comment by Sirse** [comment]
Sorry for long answer, so many work IRL...
That build contains https://github.com/Sirse/MineFantasyII-Cont/commit/cb685bd1acce0751a76b939f35b7dbbeefc80028 commit, which enables support for any stones with "stone" oredict entry.

[MineFantasyII-2.8.14.6.zip](https://github.com/Sirse/MineFantasyII-Cont/files/2740058/MineFantasyII-2.8.14.6.zip)
