### ISSUE TITLE
Script examples?

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [Sirse/MineFantasyII-Cont#45]
In lieu of a guide, if anyone could link to Minetweaker scripts using Minefantasy crafting mechanics or modpacks with such scripts in them that would be helpful.

**Comment by Sirse** [comment]
100% working handlers - https://pastebin.com/67xirRHq
Anvil, Carpenters bench, Cooking, Crucible, Forge, Fuels, Salvage and Tanning rack tweakers requires internal changes. You can look into source code (search for @ZenMethod declaration) and try to use it in your scripts, but i not sure, whats  thems works  correctly - https://github.com/Sirse/MineFantasyII-Cont/tree/master/src/main/java/minefantasy/mf2/integration/minetweaker/tweakers
