### ISSUE TITLE
Crash with the armor tad

### ISSUE THREAD

**Issue by frizette** [Sirse/MineFantasyII-Cont#48]
Hi when I open the tab "armor" or "food" with the creative menu, my game crash and i've this for the crash:
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 05/02/19 21:34
Description: Rendering screen

java.lang.ArrayIndexOutOfBoundsException: -96
	at org.lwjgl.input.Keyboard.getKeyName(Keyboard.java:429)
	at minefantasy.mf2.item.ClientItemsMF.showSpecials(ClientItemsMF.java:27)
	at minefantasy.mf2.mechanics.EventManagerMF.setTooltip(EventManagerMF.java:699)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_76_EventManagerMF_setTooltip_ItemTooltipEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:162)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:626)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:104)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146285_a(GuiContainerCreative.java:734)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:171)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1455)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.lwjgl.input.Keyboard.getKeyName(Keyboard.java:429)
	at minefantasy.mf2.item.ClientItemsMF.showSpecials(ClientItemsMF.java:27)
	at minefantasy.mf2.mechanics.EventManagerMF.setTooltip(EventManagerMF.java:699)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_76_EventManagerMF_setTooltip_ItemTooltipEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:162)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:626)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:104)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146285_a(GuiContainerCreative.java:734)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:171)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (221, 84). Absolute: (885, 743)
	Screen size: Scaled: (480, 270). Absolute: (1920, 1080). Scale factor of 4

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Bugma'/199, l='MpServer', x=21,29, y=238,62, z=-5,41]]
	Chunk stats: MultiplayerChunkCache: 1016, 1025
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,4,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 12665 game time, 12665 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 81 total; [TribesmanEntity['Tribesman'/129, l='MpServer', x=55,28, y=237,00, z=-47,78], TribesmanEntity['Tribesman'/130, l='MpServer', x=55,72, y=237,00, z=-46,50], TribesmanEntity['Tribesman'/514, l='MpServer', x=62,50, y=237,00, z=-82,50], TribesmanEntity['Tribesman'/131, l='MpServer', x=62,78, y=237,00, z=-0,50], TribesmanEntity['Tribesman'/132, l='MpServer', x=63,75, y=237,00, z=-14,53], TribesmanEntity['Tribesman'/133, l='MpServer', x=60,34, y=237,00, z=26,50], TribesmanEntity['Tribesman'/389, l='MpServer', x=-12,50, y=237,00, z=33,50], EntityItem['item.item.spruceseed'/134, l='MpServer', x=54,97, y=237,13, z=25,16], TribesmanEntity['Tribesman'/518, l='MpServer', x=62,43, y=237,00, z=-16,58], EntityItem['item.item.spruceseed'/135, l='MpServer', x=56,69, y=241,63, z=29,59], TribesmanEntity['Tribesman'/519, l='MpServer', x=59,50, y=237,00, z=-17,50], TribesmanEntity['Tribesman'/393, l='MpServer', x=64,50, y=237,00, z=-85,50], TribesmanEntity['Tribesman'/138, l='MpServer', x=67,50, y=237,00, z=-2,50], TribesmanEntity['Tribesman'/522, l='MpServer', x=77,50, y=237,00, z=40,50], TribesmanEntity['Tribesman'/139, l='MpServer', x=67,56, y=237,00, z=5,25], TribesmanEntity['Tribesman'/395, l='MpServer', x=60,50, y=237,00, z=-83,50], TribesmanEntity['Tribesman'/523, l='MpServer', x=80,50, y=237,00, z=41,50], EntitySheep['Sheep'/141, l='MpServer', x=71,16, y=237,00, z=-12,19], EntityItem['item.item.spruceseed'/142, l='MpServer', x=67,22, y=244,13, z=-2,06], EntitySheep['Sheep'/143, l='MpServer', x=78,97, y=237,00, z=13,06], TribesmanEntity['Tribesman'/529, l='MpServer', x=-51,38, y=237,00, z=24,25], EntitySheep['Sheep'/146, l='MpServer', x=72,06, y=237,00, z=22,97], TribesmanEntity['Tribesman'/530, l='MpServer', x=-55,50, y=237,00, z=15,50], EntityItem['item.item.spruceseed'/147, l='MpServer', x=64,63, y=237,13, z=16,03], TribesmanEntity['Tribesman'/531, l='MpServer', x=-53,50, y=237,00, z=15,50], EntityItem['item.item.spruceseed'/148, l='MpServer', x=67,19, y=237,13, z=17,16], EntitySheep['Sheep'/149, l='MpServer', x=67,13, y=237,00, z=19,13], TribesmanEntity['Tribesman'/278, l='MpServer', x=30,50, y=237,00, z=-40,50], TribesmanEntity['Tribesman'/280, l='MpServer', x=-54,50, y=237,00, z=6,50], TribesmanEntity['Tribesman'/25, l='MpServer', x=-53,50, y=237,00, z=-53,50], TribesmanEntity['Tribesman'/26, l='MpServer', x=-55,50, y=237,00, z=7,50], TribesmanEntity['Tribesman'/282, l='MpServer', x=-53,50, y=237,00, z=4,50], TribesmanEntity['Tribesman'/410, l='MpServer', x=-10,50, y=237,00, z=68,50], TribesmanEntity['Tribesman'/27, l='MpServer', x=-51,50, y=237,00, z=5,50], TribesmanEntity['Tribesman'/411, l='MpServer', x=-4,78, y=237,00, z=66,63], TribesmanEntity['Tribesman'/412, l='MpServer', x=-8,50, y=237,00, z=65,50], TribesmanEntity['Tribesman'/29, l='MpServer', x=-50,50, y=237,00, z=6,50], TribesmanEntity['Tribesman'/413, l='MpServer', x=-6,50, y=237,00, z=64,50], TribesmanEntity['Tribesman'/30, l='MpServer', x=-53,50, y=237,00, z=7,50], TribesmanEntity['Tribesman'/32, l='MpServer', x=-44,50, y=237,00, z=-81,50], TribesmanEntity['Tribesman'/34, l='MpServer', x=-39,16, y=237,00, z=-83,50], TribesmanEntity['Tribesman'/164, l='MpServer', x=96,50, y=237,00, z=-81,50], TribesmanEntity['Tribesman'/165, l='MpServer', x=98,50, y=237,00, z=-82,50], TribesmanEntity['Tribesman'/166, l='MpServer', x=98,44, y=237,00, z=-79,47], TribesmanEntity['Tribesman'/41, l='MpServer', x=-44,38, y=237,00, z=38,91], EntityItem['item.item.spruceseed'/42, l='MpServer', x=-40,66, y=237,13, z=38,97], EntityItem['item.item.spruceseed'/298, l='MpServer', x=28,84, y=237,13, z=-23,38], EntityItem['item.item.spruceseed'/44, l='MpServer', x=-41,41, y=237,13, z=39,06], TribesmanEntity['Tribesman'/301, l='MpServer', x=-23,50, y=237,00, z=21,50], TribesmanEntity['Tribesman'/302, l='MpServer', x=-22,50, y=237,00, z=20,50], TribesmanEntity['Tribesman'/303, l='MpServer', x=-53,50, y=237,00, z=10,50], EntityItem['item.item.spruceseed'/51, l='MpServer', x=-20,06, y=237,13, z=-69,75], EntityItem['item.item.spruceseed'/55, l='MpServer', x=-21,31, y=239,63, z=27,44], EntityItem['item.item.spruceseed'/56, l='MpServer', x=-24,88, y=237,13, z=24,53], EntitySheep['Sheep'/57, l='MpServer', x=-16,97, y=237,00, z=27,06], EntityItem['item.item.spruceseed'/58, l='MpServer', x=-21,19, y=245,75, z=24,72], TribesmanEntity['Tribesman'/61, l='MpServer', x=-14,50, y=237,00, z=-52,50], EntityItem['item.item.spruceseed'/62, l='MpServer', x=-12,41, y=240,63, z=-50,81], TribesmanEntity['Tribesman'/63, l='MpServer', x=-20,24, y=237,00, z=-10,41], TribesmanEntity['Tribesman'/64, l='MpServer', x=-11,41, y=237,00, z=-1,63], EntityItem['item.item.spruceseed'/66, l='MpServer', x=-15,97, y=237,13, z=24,31], EntitySheep['Sheep'/67, l='MpServer', x=-8,69, y=237,00, z=32,19], EntitySheep['Sheep'/68, l='MpServer', x=6,03, y=237,00, z=46,97], EntityClientPlayerMP['Bugma'/199, l='MpServer', x=21,29, y=238,62, z=-5,41], TribesmanEntity['Tribesman'/81, l='MpServer', x=15,69, y=237,00, z=-46,63], TribesmanEntity['Tribesman'/83, l='MpServer', x=12,59, y=237,00, z=-8,69], EntitySheep['Sheep'/84, l='MpServer', x=10,03, y=237,00, z=39,03], TribesmanEntity['Tribesman'/92, l='MpServer', x=21,34, y=237,00, z=-40,53], TribesmanEntity['Tribesman'/95, l='MpServer', x=16,59, y=237,00, z=-34,94], EntityItem['item.item.spruceseed'/96, l='MpServer', x=17,38, y=240,13, z=-38,09], TribesmanEntity['Tribesman'/97, l='MpServer', x=21,72, y=237,00, z=-21,75], EntityItem['item.item.spruceseed'/100, l='MpServer', x=28,44, y=237,13, z=-21,19], EntityItem['item.item.spruceseed'/101, l='MpServer', x=25,97, y=237,13, z=-18,69], TribesmanEntity['Tribesman'/102, l='MpServer', x=38,16, y=237,00, z=6,50], TribesmanEntity['Tribesman'/109, l='MpServer', x=34,41, y=237,00, z=-44,44], TribesmanEntity['Tribesman'/110, l='MpServer', x=32,38, y=237,00, z=-37,72], TribesmanEntity['Tribesman'/111, l='MpServer', x=32,50, y=237,00, z=4,38], TribesmanEntity['Tribesman'/112, l='MpServer', x=33,68, y=237,00, z=-4,32], TribesmanEntity['Tribesman'/113, l='MpServer', x=33,53, y=237,00, z=34,75], TribesmanEntity['Tribesman'/505, l='MpServer', x=-24,50, y=237,00, z=-16,50], EntityItem['item.item.spruceseed'/127, l='MpServer', x=49,69, y=237,13, z=-51,53]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:425)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 496671616 bytes (473 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 Optifine OptiFine_1.7.10_HD_U_E7 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHIJAAAA	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (Custom-NPCs-Mod-1.7.10.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.2_1.7.10.jar) 
	UCHIJAAAA	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.7.10.jar) 
	UCHIJAAAA	DragonMounts{r41-1.7.10} [Dragon Mounts] (Dragon-Mounts-Mod-1.7.10.jar) 
	UCHIJAAAA	dynamictrees{1.7.10-0.7.2c} [Dynamic Trees] (DynamicTrees-1.7.10-0.7.2c.jar) 
	UCHIJAAAA	liege{a1} [Medieval mobs mod, part of Liege mod] (Medieval-Mobs-Mod-1.7.10.jar) 
	UCHIJAAAA	minefantasy2{Alpha_2.8.12} [MineFantasyII] (MineFantasyII-2.8.12.jar) 
	UCHIJAAAA	Roguelike{1.4.4} [Roguelike Dungeons] (roguelike-1.7.10-1.4.4.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-dist.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 416.34' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Launched Version: 1.7.10-Forge10.13.4.1558-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 1050 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 416.34, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [vanilla]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 416.34
	OpenGlRenderer: GeForce GTX 1050 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

sorry for my english, I'm french

**Comment by Sirse** [comment]
This is LWJGL related issue, not MF. Try to remove options.txt
