### ISSUE TITLE
Constant TileEntity synchronization

### ISSUE THREAD

**Issue by Sirse** [Sirse/MineFantasyII-Cont#5]
Constant Server>Client synchronization: every second most TE sends own custom update packet.
Custom packets are better solution than using getDescriptionPacket and onDataPacket methods (reduced packet size), but in MF they are used for dirty things.
That causes REALLY huge traffic/bandwidth usage (about 1.8TB outgoing traffic per mouth and 4mb/sec of bandwidth).

Sync should be runned only on TE's condition change (e.g: when player adds fuel to firepit).
All time calculations should be double-sided (on client for tooltips and GUIs and on server for data validation).

Referenced issue: https://github.com/AnonymousProductions/MineFantasyII-Cont/issues/9

_Sorry me my bad english, i'm russian._

**Comment by Sirse** [comment]
![0d34211b8464fbed](https://user-images.githubusercontent.com/3335371/29459130-78cb5084-844c-11e7-9bae-1dc8ab301b3a.PNG)
![1e61415fd1ed989e_censored](https://user-images.githubusercontent.com/3335371/29459132-7b569e80-844c-11e7-9e15-22b5db3b3c7a.jpg)

**Comment by Yesterday17** [comment]
Another report [here](https://1drv.ms/u/s!Aof9Y87fPp4thGLfGcQHoT8P165l)~
Great improvement compared with the former version, hope to optimize further.
A serious problem is that its packets are almost empty(with about 20% of space used), so it's here you can also do efforts to make it better.

**Comment by Sirse** [comment]
@yesterday17, "empty" packets, if i correctly understand you, are size optimization.
MF uses custom TEUpdate packets to reduce their size, it sends only changed values, but sends messages every second.

**Comment by Yesterday17** [comment]
Sure, just like this: 
![tra](https://user-images.githubusercontent.com/8667822/29598385-2a3f40da-87fb-11e7-8c31-bd5ee0b9f71f.PNG)
The dots are 0 in packets and you can see there're too many space not used but sent in packet, which used great amount of network resource.

**Comment by Sirse** [comment]
Should be fixed via https://github.com/Sirse/MineFantasyII-Cont/pull/8 pull request.
Thx to @yesterday17, i know about PlayerManager's  methods getPlayersWatchingChunk and sendToAllWatching, but don't know about Railcraft workaround.

**Comment by Yesterday17** [comment]
@Sirse Sadly, #8  only reduced the packet sending, but didn't do anything about the packet itself. The structure of the packet still has some problems, and i don't know much about this...
