### ISSUE TITLE
the flyse-ae branch

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [Sirse/MineFantasyII-Cont#57]
Does anyone have a backup of his code? The new glassmaking sounded interesting.

**Comment by Zaxar163** [comment]
https://github.com/Zaxar163/MineFantasyII-Cont
Restore of this backup. And who are you?

**Comment by Zaxar163** [comment]
And your account seems to be one-use.

**Comment by Zaxar163** [comment]
@Sirse close issue. Also may be you need some help?

**Comment by bHXDgiuMa5yLHyC8** [comment]
Thank you!
